# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a059d6c6a75503dcec5203d75a643026ac0cd0d54ed199085b9f2c81753a60a1a63d20acecb92888c2c8eab8dab18073490a2e6c6e3d71b8e2772f551bcb1624

test:
  secret_key_base: 73c03c282d97af5007ca1b225261b83228e2766d05cf2d3d822f16ed539ad7594a8382857b601b6485ba5e857f1d45b38ddf28c51fad7f27e332a0eec734ea01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
